FROM ubuntu:xenial

#Default branch name develop
ARG BRANCH_NAME=master
#Default
ARG REPO_SLUG=donu/donu
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo
#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1

COPY donu.tar.gz /donu.tar.gz
RUN tar -xvf /donu.tar.gz

#xenial
#Missing requirement: libtool
RUN apt install -yqq libtool-bin
RUN cd /donu/scripts/windows-crosscompile && ./dependencies.sh
RUN cd /donu && scripts/windows-crosscompile/compile-donu.sh
