- hosts: all
  vars_files:
    - vars.yml
  become: true

  tasks:
    - include_tasks: tasks/install_system_dependencies.yml
      tags: [ system_dependencies ]

    - include_tasks: tasks/donu.yml
      tags: [ donu ]


