FROM debian:stretch

#Default branch name develop
ARG BRANCH_NAME=master
#Default
ARG REPO_SLUG=donito-inc/donu
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
	git \
	sudo

#RUN git clone $REPO_URL --branch $BRANCH_NAME --single-branch --depth 1 

COPY donu.tar.gz /donu.tar.gz
RUN tar -xvf /donu.tar.gz

RUN cd /donu && ./scripts/dependencies-ubuntu.sh && ./scripts/install-ubuntu.sh && \
	apt-get purge git build-essential -qy && \
	apt-get autoremove -qy && \
	apt-get clean
